# Laboratory Task 5

##### Pytorch Exercise

1. Perform Standard Imports

In [1]:
import torch
import numpy as np
import sys

2. Create a function called set_seed() that accepts seed: int as a parameter, this function must return nothing but just set the seed to a certain value.

In [2]:
def set_seed(seed: int):
    np.random.seed(seed)
    torch.manual_seed(seed)

3. Create a NumPy array called "arr" that contains 6 random integers between 0 (inclusive) and 5 (exclusive), call the set_seed() function and use 42 as the seed parameter.

In [3]:
arr = np.random.randint(0,5,6)

set_seed(42)

4. Create a tensor "x" from the array above

In [4]:
x = torch.tensor(arr)
x

tensor([4, 1, 1, 3, 0, 4])

5. Change the dtype of x from int32 to int64

In [5]:
x = x.type(torch.int64)
print(x.dtype)

torch.int64


6. Reshape x into a 3x2 tensor

In [6]:
x = x.reshape(3,2)
x.view_as(x)

tensor([[4, 1],
        [1, 3],
        [0, 4]])

7. Return the right-hand column of tensor x

In [7]:
x = x
rhc = x[:, 1:]
rhc

tensor([[1],
        [3],
        [4]])

8. Without changing x, return a tensor of square values of x

In [8]:
x = x
sq_val = x ** 2
sq_val

tensor([[16,  1],
        [ 1,  9],
        [ 0, 16]])

9. Create a tensor y with the same number of elements as x, that can be matrix-multiplied with x

In [9]:
y = torch.randint(0, 5, (2, 3))
y

tensor([[2, 2, 1],
        [4, 1, 0]])

10. Find the matrix product of x and y.

In [10]:
matrix_prod = torch.matmul(x, y)
matrix_prod

tensor([[12,  9,  4],
        [14,  5,  1],
        [16,  4,  0]])