# Laboratory Task 5 - Pytorch Exercise

##### Name: Visaviern Mosqueda

##### Year & Section: DS4A

1. Perform Standard Imports

In [3]:
pip install torch

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 887.9/887.9 MB 15.3 MB/s  0:00:20m0:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 594.3/594.3 MB 22.7 MB/s  0:00:12m0:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 14.0 MB/s  0:00:006m0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.0/88.0 MB 52.4 MB/s  0:00:016m0:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 954.8/954.8 kB 33.0 MB/s  0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 706.8/706.8 MB 20.8 MB/s  0:00:14m0:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.1/193.1 MB 54.2 MB/s  0:00:03m0:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 51.1 MB/s  0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.6/63.6 MB 53.3 MB/s  0:00:016m0:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 267.5/267.5 MB 47.0 MB/s  0:00:05m0:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 288.2/288.2 MB 48.2 MB/s  0:00:05m0:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

In [4]:
import torch
import numpy as np
import sys

2. Create a function called set_seed() that accepts seed: int as a parameter, this function must return nothing but just set the seed to a certain value.

In [5]:
def set_seed(seed: int):
    np.random.seed(seed)
    torch.manual_seed(seed)

3. Create a NumPy array called "arr" that contains 6 random integers between 0 (inclusive) and 5 (exclusive), call the set_seed() function and use 42 as the seed parameter.

In [6]:
arr = np.random.randint(0,5,6)

set_seed(42)

4. Create a tensor "x" from the array above

In [7]:
x = torch.tensor(arr)
x

tensor([2, 2, 4, 1, 3, 2])

5. Change the dtype of x from int32 to int64

In [8]:
x = x.type(torch.int64)
print(x.dtype)

torch.int64


6. Reshape x into a 3x2 tensor

In [9]:
x = x.reshape(3,2)
x.view_as(x)

tensor([[2, 2],
        [4, 1],
        [3, 2]])

7. Return the right-hand column of tensor x

In [10]:
x = x
rhc = x[:, 1:]
rhc

tensor([[2],
        [1],
        [2]])

8. Without changing x, return a tensor of square values of x

In [11]:
x = x
sq_val = x ** 2
sq_val

tensor([[ 4,  4],
        [16,  1],
        [ 9,  4]])

9. Create a tensor y with the same number of elements as x, that can be matrix-multiplied with x

In [13]:
y = torch.randint(0, 5, (2, 3))
y

tensor([[2, 2, 1],
        [4, 1, 0]])

10. Find the matrix product of x and y.

In [14]:
matrix_prod = torch.matmul(x, y)
matrix_prod

tensor([[12,  6,  2],
        [12,  9,  4],
        [14,  8,  3]])