# Laboratory Task 5

##### Pytorch Exercise

1. Perform Standard Imports

In [1]:
import torch
import numpy as np
import sys

ModuleNotFoundError: No module named 'torch'

2. Create a function called set_seed() that accepts seed: int as a parameter, this function must return nothing but just set the seed to a certain value.

In [3]:
def set_seed(seed: int):
    np.random.seed(seed)
    torch.manual_seed(seed)

3. Create a NumPy array called "arr" that contains 6 random integers between 0 (inclusive) and 5 (exclusive), call the set_seed() function and use 42 as the seed parameter.

In [4]:
arr = np.random.randint(0,5,6)

set_seed(42)

4. Create a tensor "x" from the array above

In [5]:
x = torch.tensor(arr)
x

tensor([1, 2, 2, 3, 1, 0])

5. Change the dtype of x from int32 to int64

In [6]:
x = x.type(torch.int64)
print(x.dtype)

torch.int64


6. Reshape x into a 3x2 tensor

In [7]:
x = x.reshape(3,2)
x.view_as(x)

tensor([[1, 2],
        [2, 3],
        [1, 0]])

7. Return the right-hand column of tensor x

In [8]:
x = x
rhc = x[:, 1:]
rhc

tensor([[2],
        [3],
        [0]])

8. Without changing x, return a tensor of square values of x

In [9]:
x = x
sq_val = x ** 2
sq_val

tensor([[1, 4],
        [4, 9],
        [1, 0]])

9. Create a tensor y with the same number of elements as x, that can be matrix-multiplied with x

In [10]:
y = torch.randint(0, 5, (2, 3))
y

tensor([[2, 2, 1],
        [4, 1, 0]])

10. Find the matrix product of x and y.

In [11]:
matrix_prod = torch.matmul(x, y)
matrix_prod

tensor([[10,  4,  1],
        [16,  7,  2],
        [ 2,  2,  1]])